name: TheBasics
version: 1.0
main: io.github.GoldenDeveloper79.TheBasics.TheBasics
description: A basic set of functions for Minecraft servers.
commands:
  ban:
    description: Bans a player from the server.
    usage: /ban <name> <reason>.
  feed:
    description: Feeds yourself or another player.
    usage: /feed <name>.
  fly:
    description: Toggles flying for yourself or another player.
    usage: /fly <name>.
  give:
    description: Gives yourself or another player an item.
    usage: /give <name> <itemID:itemData/itemName> <amount>.
  heal:
    description: Heals yourself or another player.
    usage: /heal <name>.
  kick:
    description: Kicks a player from the server.
    usage: /kick <name> <reason>.
  playtime:
    description: Gets the play time of yourself or another player.
    usage: /playtime <name>.
  ptime:
    description: Gets the play time of yourself or another player.
    usage: /ptime <name>.