name: TheBasics
version: 1.09
main: io.github.GoldenDeveloper79.TheBasics.TheBasics
description: A basic set of functions for Minecraft servers.
author: [GoldenDeveloper]
softdepend: [Vault]
commands:
  back:
    description: Teleports yourself to your last location.
    usage: /back.
    aliases: [b]
  balance:
    description: Retrieves or modifies the balance of yourself or another player.
    usage: /balance <set/take/add> <name> <amount>.
    aliases: [bal]
  ban:
    description: Bans a player from the server.
    usage: /ban <name> <reason>.
  clearinventory:
    description: Clears your or another players inventory.
    usage: /clearinventory <name>.
    aliases: [ci]
  deletehome:
    description: Deletes one of your homes.
    usage: /deletehome <name>.
    aliases: [delhome]
  enchant:
    description: Enchants an item in your hand.
    usage: /enchant <enchant> <level>
  feed:
    description: Feeds yourself or another player.
    usage: /feed <name>.
  fly:
    description: Toggles flying for yourself or another player.
    usage: /fly <name>.
  flyspeed:
    description: Changes your fly speed.
    usage: /flyspeed <speed>.
  gamemode:
    description: Change the gamemode of yourself or another player.
    usage: /gamemode <name> <mode>.
    aliases: [gm]
  give:
    description: Gives yourself or another player an item.
    usage: /give <name> <itemID:itemData/itemName> <amount>.
  group:
    description: Create groups, set a player to group, and get a player group.
    usage: /group <set/create/get/prefix/addpermission/removepermission> <player/group> <group>.
  heal:
    description: Heals yourself or another player.
    usage: /heal <name>.
  help:
    description: Sends the help pages to yourself or another player.
    usage: /help <name> <page>.
    aliases: [?]
  home:
    description: Teleports yourself to a home.
    usage: /home <name>.
  ignore:
    description: Ignores a player on the server.
    usage: /ignore <name>.
  info:
    description: Retrieves information about a player.
    usage: /info <name>.
  kick:
    description: Kicks a player from the server.
    usage: /kick <name> <reason>.
  kit:
    description: Give yourself a kit.
    usage: /kit <name>.
  list:
    description: Retrieves a list of online players.
    usage: /list <page>.
  message:
    description: Message a player on the server.
    usage: /message <name> <message>.
    aliases: [msg, tell]
  mute:
    description: Mutes a player on the server.
    usage: /mute <name> <time><unit y/w/d/h/m/s> <reason>.
  nick:
    description: Changes the displayname of yourself.
    usage: /nick <name>
  pay:
    description: Give another player money.
    usage: /pay <name>.
  playtime:
    description: Gets the play time of yourself or another player.
    usage: /playtime <name>.
    aliases: [ptime]
  repair:
    description: Repairs an item that you are holding in your hand.
    usage: /repair.
  reply:
    description: Replies to a player who sent you a message.
    usage: /reply <message>.
    aliases: [r]
  rules:
    description: Sends the rules to yourself or another player.
    usage: /rules <name> <page>.
  sethome:
    description: Sets a home at your location.
    usage: /sethome <name>.
  setspawn:
    description: Sets a spawn for the world at your location.
    usage: /setspawn.
  setwarp:
    description: Sets a warp at your location.
    usage: /setwarp <name>.
  spawn:
    description: Teleport yourself to spawn.
    usage: /spawn.
  speed:
    description: Changes your walking speed.
    usage: /speed <speed>.
  teleport:
    description: Teleport yourself to a player forcefully.
    usage: /teleport <name>.
    aliases: [tp]
  teleportposition:
    description: Teleport yourself to coordinates.
    usage: /teleportposition <world> <x> <y> <z>.
    aliases: [tppos]
  teleportrequest:
    description: Request to teleport to another player.
    usage: /teleportrequest <name>.
    aliases: [tr]
  teleportrequestaccept:
    description: Accept a teleport request.
    usage: /teleportrequestaccept.
    aliases: [traccept]
  teleportrequestdeny:
    description: Deny a teleport request.
    usage: /teleportrequestdeny.
    aliases: [trdeny]    
  tempban:
    description: Temporarily ban a player from the server.
    usage: /tempban <name> <time><unit y/w/d/h/m/s> <reason>
  time:
    description: Gets the time or sets the time of the world you are in.
    usage: /time set <day/night>.
  unban:
    description: Unbans a player from the server.
    usage: /unban <name>.
  unmute:
    description: Unmutes a player on the server.
    usage: /unmute <name>
  vanish:
    description: Vanish yourself or another player.
    usage: /vanish <name>.
    aliases: [v]
  warp:
    description: Gets a list of warps or teleport yourself to a warp.
    usage: /warp <name>.
  warn:
    description: Warns a player on the server.
    usage: /warn <player> <reason>.
  weather:
    description: Changes the weather in your world.
    usage: /weather <sun/rain>.